### ISSUE TITLE
[FEATURE] 好き度を設定する

### ISSUE THREAD

**Issue by eraser5th** [Zli-UoA/ryouomoi-checker-frontend#110]
## 提案の詳細

好き度を設定できる様にする

## その他

**Comment by matumoto1234** [comment]
usePopup に含めようかと思ってました

**Comment by eraser5th** [comment]
外部のとの繋ぎ込みとか色々あるし別にしていい様な気がします

**Comment by matumoto1234** [comment]
一回閉じてしまった #112 をやります
useFetch を使わない方が適切に実装できるかも

**Comment by matumoto1234** [comment]
ブランチをあっちで切って実装してしまったのであっちの issue 番号でプルリクエストだすかも
