### ISSUE TITLE
[FEATURE] pagesを仮作成

### ISSUE THREAD

**Issue by eraser5th** [Zli-UoA/ryouomoi-checker-frontend#30]
## 提案の詳細

react-router-domのインストール

pagesを仮作成
pagesに関するStorybookを書く（これも仮）
pagesをまとめるindex.tsx？をBrouserRouterでラップする

## 動機

作るものをプロジェクトに配置しておきたい

## その他

**Comment by matumoto1234** [comment]
BrowserRouter

**Comment by matumoto1234** [comment]
まがぜだ！
