### ISSUE TITLE
[FEATURE] HomePageを作成

### ISSUE THREAD

**Issue by eraser5th** [Zli-UoA/ryouomoi-checker-frontend#63]
## 提案の詳細

HomePageを作成

<img width="305" alt="スクリーンショット 2022-02-18 14 45 32" src="https://user-images.githubusercontent.com/83107074/154625096-e2f3c2b7-23fc-4aea-a57c-adafcf3f8ec4.png">

これ

## その他

**Comment by matumoto1234** [comment]
#72 のあとに作ります
