### ISSUE TITLE
[FEATURE] アイコンの白版を作成

### ISSUE THREAD

**Issue by eraser5th** [Zli-UoA/ryouomoi-checker-frontend#64]
## 提案の詳細

アイコンの白版を作成

## 動機

よくよくみたら黒のアイコンなんかなかった

## その他

**Comment by matumoto1234** [comment]
svg 持ってきていい感じに white にするだけをします

**Comment by matumoto1234** [comment]
持ってくるもの

![image](https://user-images.githubusercontent.com/55180183/154659801-28522789-af01-476f-9ec2-478d1319edc1.png)

**Comment by matumoto1234** [comment]
検索アイコンだけ 24px のままで

**Comment by matumoto1234** [comment]
Google Material Fonts から持ってきます
一旦全部もってくればええか

**Comment by matumoto1234** [comment]
どうやらコンポーネントとして import できるっぽいので、どこかに .svg ファイルをまとめたディレクトリを作ってそこから import します

- [参考](https://qiita.com/nbstsh/items/01ed86915397064216ab)
