### ISSUE TITLE
[FEATURE] usePopupの作成

### ISSUE THREAD

**Issue by eraser5th** [Zli-UoA/ryouomoi-checker-frontend#66]
## 提案の詳細

usePopupの作成

<img width="609" alt="スクリーンショット 2022-02-18 14 52 51" src="https://user-images.githubusercontent.com/83107074/154625868-3c861ca5-4b2b-4021-aa27-1f637313d6c3.png">

これ

## その他

**Comment by matumoto1234** [comment]
この issue に heartRating コンポーネント（名称は仮）の作成も含まれてますか

**Comment by matumoto1234** [comment]
issue 分けてもいいかもしれないです（別の issue で heartRating コンポーネント作りたい）

**Comment by matumoto1234** [comment]
がんばります

**Comment by matumoto1234** [comment]
これどういう実装にするのがいいんだ

**Comment by matumoto1234** [comment]
天から発想が降ってきた

`usePopup()` で以下が返る
```tsx
isOpening: boolean
openPopup: children をもつボタンのようなもの
selectedHeartsCount: ValidNumber
Popup: React.VFC
```
